### ISSUE TITLE
No Activity found to handle Intent crash

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-Android-SDK#17]
Not sure if this used to happen with the older SDK. But would it be possible to fail silently in case Play Services is not available? Considering that AdMob works without Play Services, it'd be nice if MobFox doesn't crash the app.

```
E/MobFoxLog: GooglePlayServicesNotAvailableException
             com.google.android.gms.common.GooglePlayServicesNotAvailableException
                at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzp(Unknown Source)
                at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(Unknown Source)
                at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
                at com.mobfox.sdk.GetAdvertisingIdTask.doInBackground(GetAdvertisingIdTask.java:28)
                at com.mobfox.sdk.GetAdvertisingIdTask.doInBackground(GetAdvertisingIdTask.java:16)
                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)

E/MobFoxLog: NullPointerException
             java.lang.NullPointerException
                 at com.mobfox.sdk.GetAdvertisingIdTask.doInBackground(GetAdvertisingIdTask.java:42)
                 at com.mobfox.sdk.GetAdvertisingIdTask.doInBackground(GetAdvertisingIdTask.java:16)
                 at android.os.AsyncTask$2.call(AsyncTask.java:288)
                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                 at java.lang.Thread.run(Thread.java:841)
```

**Comment by nabriski** [comment]
Hi,
Are you sure it crashed the app and this isn't just an exception trace we print out?

**Comment by ghost** [comment]
Hey thanks for the reply @nabriski 
Yes it did crash. Also, there's some more log which I missed earlier. I guess Play Services is not the actual reason then. (I was testing this on a Genymotion emulator by the way)

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=myntra://myntra.com?utm_source=Mobvista&utm_medium=Appinstall&utm_term=1&utm_campaign=Mobvista }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
       at android.app.Activity.startActivityForResult(Activity.java:3424)
       at android.app.Activity.startActivityForResult(Activity.java:3385)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
       at android.app.Activity.startActivity(Activity.java:3627)
       at android.app.Activity.startActivity(Activity.java:3595)
       at com.mobfox.sdk.MobFoxWebView$2$1.run(MobFoxWebView.java:204)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nabriski** [comment]
Yes, this is a bad ad which I will forward to our ad quality people. 
Of course, it should not crash the SDK and the fix for this is already part of our Sunday/Monday update. 
I will close this issue once the update goes live so you'll be notified.

**Comment by nabriski** [comment]
fixed in b4bd30d (1.4.0)

**Comment by ghost** [comment]
Hey @nabriski 
Slightly off topic. Is it absolutely necessary to add Play Services as a dependency?
If yes, wouldn't it be better to add an individual API as suggested by [Google](https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project) rather than all of them?

**Comment by nabriski** [comment]
Hi,
First of all, it's not absolutely necessary. We use the services to obtain the Google Ad Id. Without you will get lesser fill rates.
I will look into the link you sent and try to import only the part we need. Thanks!
