### ISSUE TITLE
NullPointerException in ResourceManager. Missing .mustache files?

### ISSUE THREAD

**Issue by monkeyinmysoup** [mobfox/MobFox-Android-SDK#25]
I'm getting many crash reports in my app, originating from the MobFox SDK. Unfortunately I haven't been able to reproduce the problem myself so all I have to go by is this stacktrace:

    java.lang.NullPointerException: lock == null
           at java.io.Reader.(Reader.java:64)
           at java.io.InputStreamReader.(InputStreamReader.java:77)
           at com.adsdk.sdk.video.ResourceManager.getStringResource(ResourceManager.java:222)
           at com.adsdk.sdk.nativeformats.creative.CreativesManager.(CreativesManager.java:50)
           at com.adsdk.sdk.nativeformats.creative.CreativesManager.getInstance(CreativesManager.java:81)
           at com.adsdk.sdk.nativeformats.NativeFormat.(NativeFormat.java:81)
           at com.adsdk.sdk.nativeformats.NativeFormatView.loadAd(NativeFormatView.java:229)
           at com.adsdk.sdk.waterfall.Banner.loadNativeFormatAd(Banner.java:181)
           at com.adsdk.sdk.waterfall.Banner.loadAdInternal(Banner.java:74)
           at com.adsdk.sdk.waterfall.Banner.access$000(Banner.java:20)
           at com.adsdk.sdk.waterfall.Banner$1.noAdFound(Banner.java:126)
           at com.adsdk.sdk.banner.AdView$5.run(AdView.java:335)
           at android.os.Handler.handleCallback(Handler.java:739)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:145)
           at android.app.ActivityThread.main(ActivityThread.java:5832)
           at java.lang.reflect.Method.invoke(Method.java)
           at java.lang.reflect.Method.invoke(Method.java:372)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Judging from the trace, `ResourceManager.getStringResource` attempts to open a resource named `"fallback_block.mustache"` (line 57 in `CreativesManager`). This file does not exist in the repo. If it is downloaded, it appears to me that perhaps this happens after it being referenced.

Perhaps the cause of the file not being present is different, but at the very least a null-check would be nice to prevent crashing.

**Comment by nabriski** [comment]
Hi,

This is where you can find the file in the rep:
https://github.com/mobfox/MobFox-Android-SDK/blob/master/src/main/resources/fallback_block.mustache

Are you using the SDK as a jar, load it from jcenter or did you compile it yourself? Also which version are you using?

**Comment by monkeyinmysoup** [comment]
Hi, thanks for your reply!
Interesting, I used github search and didn't find the files.

I'm using the latest jar. I checked and they do contain the file, so I'm not sure why they won't load. Could it be a Proguard issue?

**Comment by nabriski** [comment]
Did you follow this?
http://proguard.sourceforge.net/manual/examples.html#resourcefiles

**Comment by monkeyinmysoup** [comment]
I hadn't, but now I've added the lines to the proguard file and will hope for the best. Since I wasn't able to reproduce the issue in the first place I can't really verify that this is the solution. I'll close it and I'll keep an eye out to check if the error still occurs.

Thanks!

**Comment by nabriski** [comment]
Ok, please keep me posted if possible. 
If this works (or you find another solution) I will update the SDK installation instructions accordingly. Thanks!
