### ISSUE TITLE
handshake failure when displaying banner

### ISSUE THREAD

**Issue by matteogabella** [mobfox/MobFox-Android-SDK#31]
hi, i receive this error (in logcat) and no ad is showed
this is the complete logcat, any help?

07-11 12:36:04.185 30589-30589/com.matteogabella.chatbot E/MobFoxBanner: on error
javax.net.ssl.SSLHandshakeException: Handshake failed
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
    at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:196)
    at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:441)
    at com.android.okhttp.Connection.upgradeToTls(Connection.java:175)
    at com.android.okhttp.Connection.connect(Connection.java:155)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
    at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
    at com.mobfox.sdk.networking.MobFoxRequest$1.doInBackground(MobFoxRequest.java:151)
    at com.mobfox.sdk.networking.MobFoxRequest$1.doInBackground(MobFoxRequest.java:118)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb4069c00: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xabef5dd4:0x00000000)
    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
        ... 19 more

**Comment by asafgaber** [comment]
Hey,
looks like the sdk is trying to bring an unauthorized asset from the demand. we would like to take this creative down. is there any chance you can get hold of the response so we can identify the demand source? thanks

**Comment by matteogabella** [comment]
after a bunch of test i found out that the issue occours only when Parse
main object is istantiated...
without Parse, mobfox runs correctly...

to complete the scenario:
with the old mobfox sdk + parse there was not any problem

btw, i'm planning to remove Parse in the next months so, don't worry
excessively about this issue

thanks for your help
Matteo

2016-07-11 15:31 GMT+02:00 Asaf Gaber notifications@github.com:
