### ISSUE TITLE
java.lang.NullPointerException loading interstitial

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#41]
```
java.lang.NullPointerException
    at android.app.ContextImpl.openFileOutput(ContextImpl.java:729)
    at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:179)
    at com.mobfox.sdk.utils.Utils.write(Utils.java:107)
    at com.mobfox.sdk.dmp.DMP.update(DMP.java:93)
    at com.mobfox.sdk.dmp.DMPManager.updateDMP(DMPManager.java:26)
    at com.mobfox.sdk.bannerads.Banner.postDMP(Banner.java:510)
    at com.mobfox.sdk.bannerads.Banner.init(Banner.java:347)
    at com.mobfox.sdk.bannerads.Banner.load(Banner.java:375)
    at com.mobfox.sdk.interstitialads.InterstitialAd.load(InterstitialAd.java:288)
    at com.frostwire.android.offers.MobFoxAdNetwork$1.run(MobFoxAdNetwork.java:156)
    at android.os.Handler.handleCallback(Handler.java:730)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5136)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)
```

Our code looks like this:

``` java
public void loadNewInterstitial(Activity activity) {
        LOG.info("loadNewInterstitial invoked by thread (@"+ Thread.currentThread().hashCode() +") " + Thread.currentThread().getName());
        if (interstitialAd != null &&
            interstitialAdListener != null &&
            interstitialAdListener.isAfterBehaviorConfigured()) {
            LOG.info("loadNewInterstitial aborted. Ad is good to go already.");
            return;
        }

        long timeSinceLastLoad = System.currentTimeMillis() - lastInterstitialLoadTimestamp;
        if (timeSinceLastLoad < INTERSTITIAL_RELOAD_INTERVAL_IN_SECONDS*1000) {
            LOG.info("loadNewInterstitial aborted. too early for a load.");
            return;
        }
        LOG.info("loadNewInterstitial - time since last load: " + timeSinceLastLoad + "ms");
        lastInterstitialLoadTimestamp = System.currentTimeMillis();

        LOG.info("loadNewInterstitial - (MobFoxAdnetwork@" + this.hashCode());
        interstitialAd = new InterstitialAd(activity);
        Banner.setGetLocation(askForLocationPermissions());
        interstitialAd.setInventoryHash(Constants.MOBFOX_INVENTORY_HASH);
        interstitialAd.setListener(interstitialAdListener);

        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                // it can happen that the network is stopped right before this call
                if (interstitialAd != null) {
                    interstitialAd.load();
                    INTERSTITIAL_RELOAD_RETRIES_LEFT--;
                }
            }
        });
    }
```

Your code should look something like this, the issue seems to be triggered inside an async task:

```
AsyncTask task = new AsyncTask() {
                    protected Void doInBackground(Void... params) {
                        Info adInfo = null;

                        try {
                            adInfo = AdvertisingIdClient.getAdvertisingIdInfo(context);
                            String id = adInfo.getId();
                            Bundle bundle = new Bundle(id);
                            bundle.addData(context, DMP.this.data, IPAddress, ua);
                            String s = bundle.toString();
                            Utils.write(context, DMP.BUNDLE_FILE, s); // HERE. Might want to add some protections
                        } catch (Exception var6) {
                            ;
                        }

                        return null;
                    }
                };
```

We also recommend you start refactoring your code base to get rid of all use of  `AsyncTask`, it's one of those Android APIs that shouldn't be there. We recommend you use as few Executor Pools and just submit runnables, and then if you have to do something in the UI thread, then you invoke another runnable on the UI thread, or post it via Handler. Works better.

More on the subject
http://simonvt.net/2014/04/17/asynctask-is-bad-and-you-should-feel-bad/

**Comment by gubatron** [comment]
Also, instead of using:

`} catch (Exception e)`

you should use:

`} catch (Throwable t)`

specially on those cases you're ignoring the errors and want to avoid your API users from crashes.

In the meantime I guess we'll put a try/catch ourselves.

**Comment by nabriski** [comment]
Hi,
Thanks for the feedback, we'll open internal tasks for these. Especially for the `} catch (Throwable t)` which we already use at one place in the code but should really be using all over. Small change with a large gain.
Will close this issue when we're done.
