### ISSUE TITLE
MobFoxLocationService crash

### ISSUE THREAD

**Issue by cylonu87** [mobfox/MobFox-Android-SDK#63]
Some users have that crash on Mashmallow with MobFox-Android-SDK-Core-3.2.7b.jar. I didn't received that crash on Nougat.

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {.MainActivity}: java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3758)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
	at android.app.ActivityThread.access$1400(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:593)
	at android.os.AsyncTask.execute(AsyncTask.java:551)
	at com.mobfox.sdk.services.MobFoxLocationService.onRequestPermissionsResult(MobFoxLocationService.java:148)
	at com.mobfox.sdk.bannerads.Banner.onRequestPermissionsResult(Banner.java:624)
	...
```

**Comment by nabriski** [comment]
Thanks, we'll issue an fix update for this once we understand the problem. Will update on our progress.

**Comment by brachil** [comment]
Please try version 3.2.7c should have a fix for this crash. Thanks.
