### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/danikula/videocache/HttpProxyCacheServer$Builder

### ISSUE THREAD

**Issue by PascalSalesch** [mobfox/MobFox-Android-SDK#68]
I'm using [this](https://github.com/mobfox/MobFox-Android-SDK/wiki/Adapters#dfp) guide and [this](https://github.com/mobfox/MobFox-Android-SDK-Core-Lib/tree/master/thirdPartyNetworks/AdMob) adapter.

When I start the ad request I get the following output:

`Instantiating mediation adapter: com.mobfox.adapter.MobFoxAdapter
Server parameters: {"pubid":"747fd20d6f67858d28c615206a9a900b","gwhirl_share_location":"0"}
Could not request interstitial ad from adapter.
                                                             java.lang.NoClassDefFoundError: Failed resolution of: Lcom/danikula/videocache/HttpProxyCacheServer$Builder;
                                                                 at com.mobfox.sdk.utils.ProxyFactory.newProxy(ProxyFactory.java:26)
                                                                 at com.mobfox.sdk.utils.ProxyFactory.getProxy(ProxyFactory.java:22)
                                                                 at com.mobfox.sdk.tags.WaterfallManager.<init>(WaterfallManager.java:38)
                                                                 at com.mobfox.sdk.interstitial.Interstitial.load(Interstitial.java:65)
                                                                 at com.mobfox.adapter.MobFoxAdapter.requestInterstitialAd(MobFoxAdapter.java:169)
                                                                 at com.google.android.gms.internal.zzuw.zza(Unknown Source:137)
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:215)
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:0)
                                                                 at com.google.android.gms.internal.zztr.run(Unknown Source:130)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.danikula.videocache.HttpProxyCacheServer$Builder" on path: DexPathList[[zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/base.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yieldlove.exampleapp-AZvutoN5AGZBHEM89voaBA==/lib/x86, /system/lib, /system/vendor/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                 at com.mobfox.sdk.utils.ProxyFactory.newProxy(ProxyFactory.java:26) 
                                                                 at com.mobfox.sdk.utils.ProxyFactory.getProxy(ProxyFactory.java:22) 
                                                                 at com.mobfox.sdk.tags.WaterfallManager.<init>(WaterfallManager.java:38) 
                                                                 at com.mobfox.sdk.interstitial.Interstitial.load(Interstitial.java:65) 
                                                                 at com.mobfox.adapter.MobFoxAdapter.requestInterstitialAd(MobFoxAdapter.java:169) 
                                                                 at com.google.android.gms.internal.zzuw.zza(Unknown Source:137) 
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:215) 
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:0) 
                                                                 at com.google.android.gms.internal.zztr.run(Unknown Source:130) 
                                                                 at android.os.Handler.handleCallback(Handler.java:789) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                 at android.os.Looper.loop(Looper.java:164) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Could not request ad from mediation adapter.
                                                             android.os.RemoteException
                                                                 at com.google.android.gms.internal.zzuw.zza(Unknown Source:160)
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:215)
                                                                 at com.google.android.gms.internal.zztq.zza(Unknown Source:0)
                                                                 at com.google.android.gms.internal.zztr.run(Unknown Source:130)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

Am I missing any dependencies?

**Comment by nabriski** [comment]
Hi,

If you're installing for jar you need in your gradle:
 ```compile 'com.danikula:videocache:2.7.0'```
See:
https://github.com/mobfox/MobFox-Android-SDK#option-2-jar-installation

**Comment by PascalSalesch** [comment]
Thank you!

Successfully mediated via: com.mobfox.adapter.MobFoxAdapter!
