### ISSUE TITLE
Error in running the project after including MobFox-Android-AdMob-Adapter.jar

### ISSUE THREAD

**Issue by SmartDroidies** [mobfox/MobFox-Android-SDK#70]
**Using gradle:3.1.0-alpha06 and Android Studio 3.1 Canary 6. It is a multi featured android project.** 
```

Caused by: java.io.UncheckedIOException: java.io.IOException: Failed to read zip file 'xxx/natkati-base/lib/MobFox-Android-AdMob-Adapter.jar'.
	at com.android.build.gradle.internal.pipeline.IncrementalFileMergerTransformUtils.computeFiles(IncrementalFileMergerTransformUtils.java:240)
	at com.android.build.gradle.internal.pipeline.IncrementalFileMergerTransformUtils.lambda$toIncrementalInput$3(IncrementalFileMergerTransformUtils.java:84)
	at com.android.apkzlib.utils.CachedSupplier.get(CachedSupplier.java:81)
	at com.android.builder.merge.LazyIncrementalFileMergerInput.lambda$new$2(LazyIncrementalFileMergerInput.java:138)
	at com.android.apkzlib.utils.CachedSupplier.get(CachedSupplier.java:81)
	at com.android.builder.merge.LazyIncrementalFileMergerInput.open(LazyIncrementalFileMergerInput.java:225)
	at com.android.builder.merge.DelegateIncrementalFileMergerInput.open(DelegateIncrementalFileMergerInput.java:49)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:397)
	at com.android.builder.merge.IncrementalFileMerger.merge(IncrementalFileMerger.java:73)
	at com.android.build.gradle.internal.transforms.MergeJavaResourcesTransform.transform(MergeJavaResourcesTransform.java:411)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 107 more
Caused by: java.io.IOException: Failed to read zip file 'xxx/natkati-base/lib/MobFox-Android-AdMob-Adapter.jar'.
	at com.android.apkzlib.zip.ZFile.<init>(ZFile.java:525)
	at com.android.apkzlib.zip.ZFile.<init>(ZFile.java:447)
	at com.android.apkzlib.zip.ZFile.<init>(ZFile.java:433)
	at com.android.builder.files.RelativeFiles.fromZip(RelativeFiles.java:119)
	at com.android.build.gradle.internal.pipeline.IncrementalFileMergerTransformUtils.computeFiles(IncrementalFileMergerTransformUtils.java:238)
	... 135 more
Caused by: java.io.IOException: EOCD signature not found in the last 65557 bytes of the file.
	at com.android.apkzlib.zip.ZFile.readEocd(ZFile.java:786)
	at com.android.apkzlib.zip.ZFile.readData(ZFile.java:596)
	at com.android.apkzlib.zip.ZFile.<init>(ZFile.java:510)
	... 139 more
  
```

**Comment by SmartDroidies** [comment]
Using gradle:3.1.0-alpha06 and Android Studio 3.1 Canary 6. It is a multi featured android project.

**Comment by nabriski** [comment]
Hi,

We'll check this locally first and get back to you.

Thanks

**Comment by nabriski** [comment]
Although we didn't encounter this, we've updated this file (along with SDK 3.6.0), please try again now.
